<?php

declare(strict_types=1);

namespace App\Infrastructure\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260711080643 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE checklist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(510) NOT NULL, ordre INT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C696D2F7E3C61F9 ON checklist (owner_id)');
        $this->addSql('ALTER TABLE checklist ADD CONSTRAINT FK_5C696D2F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT fk_d338d5837e3c61f9');
        $this->addSql('DROP TABLE equipment');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(510) NOT NULL, ordre INT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d338d5837e3c61f9 ON equipment (owner_id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT fk_d338d5837e3c61f9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checklist DROP CONSTRAINT FK_5C696D2F7E3C61F9');
        $this->addSql('DROP TABLE checklist');
    }
}
