controllers:
    resource:
        path: ../src/Http/Controller/
        namespace: App\Http\Controller
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: en|fr
    defaults:
        _locale: fr
